version: "3"
services:
  app:
    build: .
    #command: bin/rails s -b "0.0.0.0"
    #env_file: .env # railsの環境変数を.envで記載する場合
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    depends_on:
      - db
    tty:
      true
  db:
    image: mysql:8
    volumes:
      - ".:/src"
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/access.cnf:/home/access.cnf:Z
      - ./docker/mysql/wait.sh:/home/wait.sh:Z
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password # 本番環境では別ファイルで管理すること
    ports:
      - "3306:3306"